when:
  - event: tag
  - event: manual
    branch: stable

labels:
  platform: linux/amd64

variables:
  artifacts_uploader_image: &artifacts_uploader_image docker.io/woodpeckercommunity/plugin-gitea-package:0.5.1
  artifacts_uploader_settings: &artifacts_uploader_settings
    user:
      from_secret: pleroma-ci-user
    password:
      from_secret: pleroma-ci-password
    owner: 'pleroma'

steps:
  build-spec:
    image: docker.io/hexpm/elixir-amd64:1.17.3-erlang-27.3.4.2-alpine-3.22.1
    environment:
      MIX_ENV: prod
      VIX_COMPILATION_MODE: PLATFORM_PROVIDED_LIBVIPS
    commands:
      - apk update --no-cache
      - apk add git build-base cmake file-dev openssl vips-dev zip
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get --only prod
      - mix pleroma.openapi_spec spec.json

  upload-spec:
    image: *artifacts_uploader_image
    settings:
      <<: *artifacts_uploader_settings
      package_name: api-docs-spec
      package_version: stable
      file_source: ./spec.json
      file_name: spec.json
      update: 'true'

  trigger-deploy:
    image: docker.io/woodpeckerci/plugin-trigger:1.1.1
    settings:
      params:
        - BRANCH=stable
      deploy: 'api-docs'
      last-successful: true
      token:
        from_secret:
          pleroma-ci-woodpecker-token
      repositories:
        - pleroma/api-docs@master
